### PR TITLE
add input formatter to show card type

### PR DESCRIPTION
**Pull request by sante85**
i have added input formatter to show card type

example
decoration: InputDecoration(
            contentPadding: EdgeInsets.only(top: 20), // add padding to adjust text
            isDense: true,
            prefixIcon: Padding(
              padding: EdgeInsets.only(top: 15), // add padding to adjust icon
              child: getCardTypeIconFromBrand(cardBrand),
            ))

var cardNumberFormatter = CardNumberFormatter(onCardBrandChanged: (brand) {
      setState(() {
        cardBrand = brand;
      });
    });

### CODE REVIEW

**Comment by ezet** [comment]
Thanks for your contribution, I'll review this as soon as I have time!

**Comment by sante85** [comment]
this is a urgent feature, i would be customize to add icon of card brand and cvc hint 4 digits for amex.

best regards

**Comment by ezet** [comment]
I'm not convinced this belongs in this library. It is completely supported to create your own custom text field with this feature if you need it. There are multiple flutter libraries that already handle both credit card input, and credit card detection, if you wish to use any of those. The UI widgets provided in this library are meant to be very lightweight, and it not the focus of the library.

**Comment by sante85** [comment]
But the UI widgets are very important for end user. this addition not load
library. can i do a pull request?

Il giorno sab 28 mar 2020 alle ore 20:24 Lars-Kristian Dahl <
notifications@github.com> ha scritto:

**Comment by sante85** [comment]
@ezet library without UI widgets is not a complete and powerful library.

**Comment by ezet** [comment]
This has been implemented using a 3rd party library

**Pull request closed without merging**
