### PR TITLE
Clean up project

### PR DESCRIPTION
**Pull request by dariotrombello**
* Fix all lint issues
* Regenerate the complete project using latest flutter sdk version
* Also fixed small other issues I found
* Bump dependencies

Requires some tests before merging.

### CODE REVIEW

**Comment by dariotrombello** [comment]
Example app works fine on android.

**Comment by ezet** [comment]
This was a large pr.. I appreciate your work, but I agree that this will require some thorough testing and review. First off, I need to request that you revert the changes to `.gitignore` related to the `.idea/` folder. Don't ignore the whole folder, but ignore the specific subfolders/files as it was before. That folder has run configurations and other useful settings that are not user-specific.

**Comment by dariotrombello** [comment]
Done. Let me know if you find anything else.

**Comment by ezet** [comment]
I will review/merge this soon, have not had time for this project lately.

**Pull request merged**
