### PR TITLE
added custom title add payment screen and generic state card form

### PR DESCRIPTION
**Pull request by ElAdrixHD**

### CODE REVIEW

**Comment by ezet** [comment]
I will review this next week

**Comment by ezet** [comment]
Please recreate this PR without deleting the .idea project folder.

**Comment by josxha** [comment]
Feature added within https://github.com/ezet/stripe-sdk/pull/126 and already available in the prerelease version.

**Comment by ezet** [comment]
Thanks @ElAdrixHD . This is is available in 5.0.0 prerelease.

**Pull request closed without merging**
